# Generated by Django 5.2.7 on 2025-10-30 06:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AICoach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "personality",
                    models.CharField(
                        choices=[
                            ("genz", "Gen-Z"),
                            ("calm", "Calm"),
                            ("friendly", "Friendly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "visitor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_coach",
                        to="home.visitor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_pose", models.CharField(max_length=100)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("misaligned_count", models.PositiveIntegerField(default=0)),
                (
                    "coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ex.aicoach",
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.visitor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("target_pose", models.CharField(max_length=100)),
                ("detected_pose", models.CharField(max_length=100)),
                (
                    "time_duration",
                    models.FloatField(default=0.0, help_text="Duration in seconds"),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("misaligned_count", models.PositiveIntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pose_logs",
                        to="ex.exercisesession",
                    ),
                ),
            ],
        ),
    ]
