# Generated by Django 5.2.7 on 2025-10-30 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        default="img1.jpg",
                        null=True,
                        upload_to="profile_photos/",
                    ),
                ),
                (
                    "health_condition",
                    models.CharField(
                        choices=[
                            ("breast_cancer", "Breast Cancer"),
                            ("thyroid", "Thyroid"),
                            ("PCOS/PCOD", "PCOS/PCOD"),
                            ("general_health", "General Health"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("had_period", models.BooleanField(default=False)),
                ("weight", models.FloatField(blank=True, null=True)),
                (
                    "energy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "symptoms",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("activities", models.TextField(blank=True, default=None, null=True)),
                ("meals", models.TextField(blank=True, default=None, null=True)),
                ("notes", models.TextField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_entries",
                        to="home.visitor",
                    ),
                ),
            ],
        ),
    ]
