# Generated by Django 5.2.7 on 2025-11-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="profile_photo",
            field=models.ImageField(
                blank=True, default="img1.png", null=True, upload_to="profile_photos/"
            ),
        ),
    ]
